name: Update mirrors

on:
  schedule:
    - cron: "17 5 * * *"

  workflow_dispatch:

jobs:
  update-mirrors:
    runs-on: ubuntu-latest

    steps:
      - name: Check if token is set
        env:
          GH_MIRRORS_TOKEN: ${{ secrets.GH_MIRRORS_TOKEN }}
        run: |
          if [ -z "$GH_MIRRORS_TOKEN" ]; then
            echo "Error: GH_MIRRORS_TOKEN is not set"
            exit 1
          fi

      - name: Update rafaelurben/pyatem-mirror from https://git.sr.ht/~martijnbraam/pyatem
        env:
          GH_MIRRORS_TOKEN: ${{ secrets.GH_MIRRORS_TOKEN }}
        run: |
          git clone --bare https://git.sr.ht/~martijnbraam/pyatem src.git
          cd src.git
          git remote add github https://$GH_MIRRORS_TOKEN@github.com/rafaelurben/pyatem-mirror.git
          git push --mirror github
