name: Update mirrors

on:
  schedule:
    - cron: "17 5 * * *"

  workflow_dispatch:

jobs:
  update-mirrors:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        include:
          - source: https://git.sr.ht/~martijnbraam/pyatem
            source_name: git.sr.ht/~martijnbraam/pyatem
            target: https://${{ secrets.GH_MIRRORS_TOKEN }}@github.com/rafaelurben/pyatem-mirror.git
            target_name: rafaelurben/pyatem-mirror
 
    steps:
      - name: Update ${{ matrix.target_name }} from ${{ matrix.source_name }}
        run: |
          git clone --bare ${{ matrix.source }} src.git
          cd src.git
          git remote add target ${{ matrix.target }}
          git push --mirror target
