name: Update mirrors

on:
  schedule:
    - cron: "17 5 * * *"

  workflow_dispatch:

jobs:
  update-mirrors:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        include:
          - source: https://git.sr.ht/~martijnbraam/pyatem
            github_repo: rafaelurben/pyatem-mirror
 
    steps:
      - name: Update ${{ matrix.github_repo }} from ${{ matrix.source }}
        env:
          GH_MIRRORS_TOKEN: ${{ secrets.GH_MIRRORS_TOKEN }}
        run: |
          git clone --bare ${{ matrix.source }} src.git
          cd src.git
          git remote add github https://$GH_MIRRORS_TOKEN@github.com/${{ matrix.github_repo }}
          git push --mirror github
